export const type = {
  CANCEL_MEMBERSHIP_REQUEST_REQUEST: "CANCEL_MEMBERSHIP_REQUEST_REQUEST",
  CANCEL_MEMBERSHIP_REQUEST_FAILURE: "CANCEL_MEMBERSHIP_REQUEST_FAILURE",
  CANCEL_MEMBERSHIP_REQUEST_SUCCESS: "CANCEL_MEMBERSHIP_REQUEST_SUCCESS",
};
